name: ride_univers_app_flutter
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Functional Programming
  dartz: ^0.10.1
  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  # Navigation
  go_router: ^13.0.0
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Location
  geolocator: ^10.1.0
  # UI
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2+1
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  # Authentication
  google_sign_in: ^6.1.6
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  # JSON Serialization
  json_annotation: ^4.9.0
  # Base de données locale
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  # Synchronisation et connectivité
  connectivity_plus: ^5.0.2
  workmanager: ^0.5.2
  laravel_exception: ^0.0.4
  get: ^4.6.6
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  permission_handler: ^11.2.1
  latlong2: ^0.9.0
  flutter_osm_plugin: ^0.70.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 